language: ruby

sudo: false

addons:
  apt:
    packages:
      - graphviz
  chrome: stable

cache:
  - apt
  - bundler

before_install:
  - sudo apt update -qq
  - sudo apt install -y chromium-chromedriver
  - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/
  - gem install bundler

rvm:
  - 2.5.3
  - 2.0.0

gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_32.gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_52.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_32.gemfile
